
//====================================================================================
// NOTE: Put '#include "FRAMEWORK\src\RCE\ExportRedir.hpp"' before 'class CAppMain: public CApplication'
//
namespace ProxyExport
{  
static vptr  ThisLibBase = nullptr;  // Must be initialized
const achar* RealLibPath = nullptr;  // Must be initialized

//------------------------------------------------------------------------------------ 
_ninline vptr _fcall ResolveExportRedir(vptr ExpProcAddr)
{
 vptr pOrig = nullptr;
 const achar* ProcName = NFWK::NPTM::NPE::GetProcInfo(ThisLibBase, ExpProcAddr); 
 if(!pOrig)pOrig = NFWK::NPTM::LoadModule(RealLibPath);    // Not GetModuleHandle since both have the same name 
 DBGMSG("ThisLibBase=%p, OrigLibBase=%p, ExpProcAddr=%p, ExpProcName=%s : %s",ThisLibBase, pOrig, ExpProcAddr, ProcName, RealLibPath);
 return NFWK::NPTM::NPE::GetProcAddr(pOrig, ProcName); 
}
//------------------------------------------------------------------------------------
#if defined(ARCH_X64)
// NOTE: Arguments number is limited!!!!!
// NOTE: Not going to be tail optimized('jmp rax')!
// TODO: Rewrite the stubs in ASM?
#define APIWRAPPER(NameAPI) extern "C" _declspec(dllexport) void _ccall NameAPI(vptr ParA, vptr ParB, vptr ParC, vptr ParD, vptr ParE, vptr ParF, vptr ParG, vptr ParH, vptr ParI, vptr ParJ, vptr ParK, vptr ParL) \
{ \
 static vptr Address = nullptr; \
 if(!Address)Address = ResolveExportRedir(& NameAPI); \
 ((void (_ccall *)(...))(Address))(ParA, ParB, ParC, ParD, ParE, ParF, ParG, ParH, ParI, ParJ, ParK, ParL); \
}
#else
// Only 'cdecl' can be exported without name mangling  
#define APIWRAPPER(NameAPI) extern "C" _declspec(dllexport, naked) void _fcall NameAPI(vptr ParA, vptr ParB, ...) \
{ \
 static vptr Address = nullptr; \
 if(!Address)Address = ResolveExportRedir(& NameAPI); \
 __asm jmp [Address]  \
}
#endif
//------------------------------------------------------------------------------------ 
// NOTE: All of the exports will be mixed and sorted alphabetically (To preserve ordinals use .def file)
// 
// version.dll
APIWRAPPER(GetFileVersionInfoA)
APIWRAPPER(GetFileVersionInfoByHandle)
APIWRAPPER(GetFileVersionInfoExA)
APIWRAPPER(GetFileVersionInfoExW)
APIWRAPPER(GetFileVersionInfoSizeA)
APIWRAPPER(GetFileVersionInfoSizeExA)
APIWRAPPER(GetFileVersionInfoSizeExW)
APIWRAPPER(GetFileVersionInfoSizeW)
APIWRAPPER(GetFileVersionInfoW)
APIWRAPPER(VerFindFileA)
APIWRAPPER(VerFindFileW)
APIWRAPPER(VerInstallFileA)
APIWRAPPER(VerInstallFileW)
APIWRAPPER(VerLanguageNameA)
APIWRAPPER(VerLanguageNameW)
APIWRAPPER(VerQueryValueA)
APIWRAPPER(VerQueryValueW) 

// cryptsp.dll
APIWRAPPER(CryptAcquireContextA)
APIWRAPPER(CryptAcquireContextW)
APIWRAPPER(CryptContextAddRef)
APIWRAPPER(CryptCreateHash)
APIWRAPPER(CryptDecrypt)
APIWRAPPER(CryptDeriveKey)
APIWRAPPER(CryptDestroyHash)
APIWRAPPER(CryptDestroyKey)
APIWRAPPER(CryptDuplicateHash)
APIWRAPPER(CryptDuplicateKey)
APIWRAPPER(CryptEncrypt)
APIWRAPPER(CryptEnumProviderTypesA)
APIWRAPPER(CryptEnumProviderTypesW)
APIWRAPPER(CryptEnumProvidersA)
APIWRAPPER(CryptEnumProvidersW)
APIWRAPPER(CryptExportKey)
APIWRAPPER(CryptGenKey)
APIWRAPPER(CryptGenRandom)
APIWRAPPER(CryptGetDefaultProviderA)
APIWRAPPER(CryptGetDefaultProviderW)
APIWRAPPER(CryptGetHashParam)
APIWRAPPER(CryptGetKeyParam)
APIWRAPPER(CryptGetProvParam)
APIWRAPPER(CryptGetUserKey)
APIWRAPPER(CryptHashData)
APIWRAPPER(CryptHashSessionKey)
APIWRAPPER(CryptImportKey)
APIWRAPPER(CryptReleaseContext)
APIWRAPPER(CryptSetHashParam)
APIWRAPPER(CryptSetKeyParam)
APIWRAPPER(CryptSetProvParam)
APIWRAPPER(CryptSetProviderA)
APIWRAPPER(CryptSetProviderExA)
APIWRAPPER(CryptSetProviderExW)
APIWRAPPER(CryptSetProviderW)
APIWRAPPER(CryptSignHashA)
APIWRAPPER(CryptSignHashW)
APIWRAPPER(CryptVerifySignatureA)
APIWRAPPER(CryptVerifySignatureW) 

// winspool.drv
APIWRAPPER(GetDefaultPrinterA)
APIWRAPPER(AbortPrinter)
APIWRAPPER(AddFormA)
APIWRAPPER(AddFormW)
APIWRAPPER(AddJobA)
APIWRAPPER(AddJobW)
APIWRAPPER(AddMonitorA)
APIWRAPPER(AddMonitorW)
APIWRAPPER(AddPortA)
APIWRAPPER(AddPortExA)
APIWRAPPER(AddPortExW)
APIWRAPPER(AddPortW)
APIWRAPPER(AddPrintProcessorA)
APIWRAPPER(AddPrintProcessorW)
APIWRAPPER(AddPrintProvidorA)
APIWRAPPER(AddPrintProvidorW)
APIWRAPPER(AddPrinterA)
APIWRAPPER(AddPrinterConnection2A)
APIWRAPPER(AddPrinterConnection2W)
APIWRAPPER(AddPrinterConnectionA)
APIWRAPPER(AddPrinterConnectionW)
APIWRAPPER(AddPrinterDriverA)
APIWRAPPER(AddPrinterDriverExA)
APIWRAPPER(AddPrinterDriverExW)
APIWRAPPER(AddPrinterDriverW)
APIWRAPPER(AddPrinterW)
APIWRAPPER(AdvancedDocumentPropertiesA)
APIWRAPPER(AdvancedDocumentPropertiesW)
APIWRAPPER(AdvancedSetupDialog)
APIWRAPPER(CheckSignatureInFile)
APIWRAPPER(ClosePrinter)
APIWRAPPER(CloseSpoolFileHandle)
APIWRAPPER(CommitSpoolData)
APIWRAPPER(ConfigurePortA)
APIWRAPPER(ConfigurePortW)
APIWRAPPER(ConnectToPrinterDlg)
APIWRAPPER(ConvertAnsiDevModeToUnicodeDevmode)
APIWRAPPER(ConvertUnicodeDevModeToAnsiDevmode)
APIWRAPPER(CorePrinterDriverInstalledA)
APIWRAPPER(CorePrinterDriverInstalledW)
APIWRAPPER(CreatePrintAsyncNotifyChannel)
APIWRAPPER(CreatePrinterIC)
APIWRAPPER(DeleteFormA)
APIWRAPPER(DeleteFormW)
APIWRAPPER(DeleteMonitorA)
APIWRAPPER(DeleteMonitorW)
APIWRAPPER(DeletePortA)
APIWRAPPER(DeletePortW)
APIWRAPPER(DeletePrintProcessorA)
APIWRAPPER(DeletePrintProcessorW)
APIWRAPPER(DeletePrintProvidorA)
APIWRAPPER(DeletePrintProvidorW)
APIWRAPPER(DeletePrinter)
APIWRAPPER(DeletePrinterConnectionA)
APIWRAPPER(DeletePrinterConnectionW)
APIWRAPPER(DeletePrinterDataA)
APIWRAPPER(DeletePrinterDataExA)
APIWRAPPER(DeletePrinterDataExW)
APIWRAPPER(DeletePrinterDataW)
APIWRAPPER(DeletePrinterDriverA)
APIWRAPPER(DeletePrinterDriverExA)
APIWRAPPER(DeletePrinterDriverExW)
APIWRAPPER(DeletePrinterDriverPackageA)
APIWRAPPER(DeletePrinterDriverPackageW)
APIWRAPPER(DeletePrinterDriverW)
APIWRAPPER(DeletePrinterIC)
APIWRAPPER(DeletePrinterKeyA)
APIWRAPPER(DeletePrinterKeyW)
APIWRAPPER(DevQueryPrint)
APIWRAPPER(DevQueryPrintEx)
APIWRAPPER(DeviceCapabilitiesA)
APIWRAPPER(DeviceCapabilitiesW)
APIWRAPPER(DeviceMode)
APIWRAPPER(DevicePropertySheets)
APIWRAPPER(DocumentEvent)
APIWRAPPER(DocumentPropertiesA)
APIWRAPPER(DocumentPropertiesW)
APIWRAPPER(DocumentPropertySheets)
APIWRAPPER(EndDocPrinter)
APIWRAPPER(EndPagePrinter)
APIWRAPPER(EnumFormsA)
APIWRAPPER(EnumFormsW)
APIWRAPPER(EnumJobsA)
APIWRAPPER(EnumJobsW)
APIWRAPPER(EnumMonitorsA)
APIWRAPPER(EnumMonitorsW)
APIWRAPPER(EnumPortsA)
APIWRAPPER(EnumPortsW)
APIWRAPPER(EnumPrintProcessorDatatypesA)
APIWRAPPER(EnumPrintProcessorDatatypesW)
APIWRAPPER(EnumPrintProcessorsA)
APIWRAPPER(EnumPrintProcessorsW)
APIWRAPPER(EnumPrinterDataA)
APIWRAPPER(EnumPrinterDataExA)
APIWRAPPER(EnumPrinterDataExW)
APIWRAPPER(EnumPrinterDataW)
APIWRAPPER(EnumPrinterDriversA)
APIWRAPPER(EnumPrinterDriversW)
APIWRAPPER(EnumPrinterKeyA)
APIWRAPPER(EnumPrinterKeyW)
APIWRAPPER(EnumPrintersA)
APIWRAPPER(EnumPrintersW)
APIWRAPPER(ExtDeviceMode)
APIWRAPPER(FindClosePrinterChangeNotification)
APIWRAPPER(FindFirstPrinterChangeNotification)
APIWRAPPER(FindNextPrinterChangeNotification)
APIWRAPPER(FlushPrinter)
APIWRAPPER(FreePrinterNotifyInfo)
APIWRAPPER(GetCorePrinterDriversA)
APIWRAPPER(GetCorePrinterDriversW)
APIWRAPPER(GetDefaultPrinterW)
APIWRAPPER(GetFormA)
APIWRAPPER(GetFormW)
APIWRAPPER(GetJobA)
APIWRAPPER(GetJobW)
APIWRAPPER(GetPrintExecutionData)
APIWRAPPER(GetPrintProcessorDirectoryA)
APIWRAPPER(GetPrintProcessorDirectoryW)
APIWRAPPER(GetPrinterA)
APIWRAPPER(GetPrinterDataA)
APIWRAPPER(GetPrinterDataExA)
APIWRAPPER(GetPrinterDataExW)
APIWRAPPER(GetPrinterDataW)
APIWRAPPER(GetPrinterDriver2A)
APIWRAPPER(GetPrinterDriver2W)
APIWRAPPER(GetPrinterDriverA)
APIWRAPPER(GetPrinterDriverDirectoryA)
APIWRAPPER(GetPrinterDriverDirectoryW)
APIWRAPPER(GetPrinterDriverPackagePathA)
APIWRAPPER(GetPrinterDriverPackagePathW)
APIWRAPPER(GetPrinterDriverW)
APIWRAPPER(GetPrinterW)
APIWRAPPER(GetSpoolFileHandle)
APIWRAPPER(InstallPrinterDriverFromPackageA)
APIWRAPPER(InstallPrinterDriverFromPackageW)
APIWRAPPER(IsValidDevmodeA)
APIWRAPPER(IsValidDevmodeW)
APIWRAPPER(OpenPrinter2A)
APIWRAPPER(OpenPrinter2W)
APIWRAPPER(OpenPrinterA)
APIWRAPPER(OpenPrinterW)
APIWRAPPER(PerfClose)
APIWRAPPER(PerfCollect)
APIWRAPPER(PerfOpen)
APIWRAPPER(PlayGdiScriptOnPrinterIC)
APIWRAPPER(PrinterMessageBoxA)
APIWRAPPER(PrinterMessageBoxW)
APIWRAPPER(PrinterProperties)
APIWRAPPER(QueryColorProfile)
APIWRAPPER(QueryRemoteFonts)
APIWRAPPER(QuerySpoolMode)
APIWRAPPER(ReadPrinter)
APIWRAPPER(RegisterForPrintAsyncNotifications)
APIWRAPPER(ReportJobProcessingProgress)
APIWRAPPER(ResetPrinterA)
APIWRAPPER(ResetPrinterW)
APIWRAPPER(ScheduleJob)
APIWRAPPER(SeekPrinter)
APIWRAPPER(SetDefaultPrinterA)
APIWRAPPER(SetDefaultPrinterW)
APIWRAPPER(SetFormA)
APIWRAPPER(SetFormW)
APIWRAPPER(SetJobA)
APIWRAPPER(SetJobW)
APIWRAPPER(SetPortA)
APIWRAPPER(SetPortW)
APIWRAPPER(SetPrinterA)
APIWRAPPER(SetPrinterDataA)
APIWRAPPER(SetPrinterDataExA)
APIWRAPPER(SetPrinterDataExW)
APIWRAPPER(SetPrinterDataW)
APIWRAPPER(SetPrinterW)
APIWRAPPER(SplDriverUnloadComplete)
APIWRAPPER(SpoolerDevQueryPrintW)
APIWRAPPER(SpoolerPrinterEvent)
APIWRAPPER(StartDocDlgA)
APIWRAPPER(StartDocDlgW)
APIWRAPPER(StartDocPrinterA)
APIWRAPPER(StartDocPrinterW)
APIWRAPPER(StartPagePrinter)
APIWRAPPER(SystemFunction035)
APIWRAPPER(UnRegisterForPrintAsyncNotifications)
APIWRAPPER(UploadPrinterDriverPackageA)
APIWRAPPER(UploadPrinterDriverPackageW)
APIWRAPPER(WaitForPrinterChange)
APIWRAPPER(WritePrinter)
APIWRAPPER(XcvDataW)  

}
//====================================================================================
